/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FamilyTreeNode = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const WithdrawalId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberId = IDL.Principal;
export const Time = IDL.Int;
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'memberId' : MemberId,
  'achievedAt' : Time,
  'description' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Withdrawal = IDL.Record({
  'status' : WithdrawalStatus,
  'memberId' : MemberId,
  'requestId' : WithdrawalId,
  'bankAccount' : IDL.Text,
  'amount' : IDL.Nat,
  'requestDate' : Time,
});
export const ContactFormId = IDL.Nat;
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ContactFormSubmission = IDL.Record({
  'id' : ContactFormId,
  'customerName' : IDL.Text,
  'packagePrice' : IDL.Nat,
  'submittedAt' : Time,
  'submittedBy' : MemberId,
  'productId' : IDL.Nat,
  'customerAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'coordinates' : Coordinates,
});
export const RegistrationFields = IDL.Record({
  'placeOfBirth' : IDL.Opt(IDL.Text),
  'country' : IDL.Opt(IDL.Text),
  'province' : IDL.Opt(IDL.Text),
  'bankAccount' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Opt(IDL.Text),
  'sameAsKtp' : IDL.Opt(IDL.Bool),
  'city' : IDL.Opt(IDL.Text),
  'completeAddress' : IDL.Opt(IDL.Text),
  'sponsorId' : IDL.Opt(MemberId),
  'fullName' : IDL.Opt(IDL.Text),
  'sealed' : IDL.Bool,
  'whatsappNumber' : IDL.Opt(IDL.Text),
  'subscriptionsVerified' : IDL.Bool,
  'nikKtp' : IDL.Opt(IDL.Text),
  'domicileAddress' : IDL.Opt(IDL.Text),
});
export const ProfileCompletionStatus = IDL.Variant({
  'incomplete' : IDL.Null,
  'complete' : IDL.Null,
});
export const BasicProfile = IDL.Record({
  'contact' : IDL.Text,
  'joinDate' : Time,
  'name' : IDL.Text,
});
export const MemberProfile = IDL.Record({
  'profileCompletionTimestamp' : IDL.Opt(Time),
  'registrationFields' : RegistrationFields,
  'profileCompletionStatus' : ProfileCompletionStatus,
  'basic' : BasicProfile,
  'profileRole' : UserRole,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'explanation' : IDL.Text,
  'description' : IDL.Text,
  'commissionRate' : IDL.Nat,
  'price' : IDL.Nat,
});
export const PurchaseStatus = IDL.Variant({
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Purchase = IDL.Record({
  'id' : IDL.Nat,
  'status' : PurchaseStatus,
  'contact' : IDL.Text,
  'purchaseDate' : Time,
  'productId' : IDL.Nat,
  'address' : IDL.Text,
  'buyerName' : IDL.Text,
});
FamilyTreeNode.fill(
  IDL.Record({
    'memberId' : MemberId,
    'registrationFields' : RegistrationFields,
    'children' : IDL.Vec(FamilyTreeNode),
    'basic' : BasicProfile,
  })
);
export const IncentiveComponent = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const Theme = IDL.Record({
  'backgroundColor' : IDL.Text,
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const Level = IDL.Nat;
export const CommissionAmount = IDL.Nat;
export const Transaction = IDL.Record({
  'memberId' : MemberId,
  'date' : Time,
  'level' : Level,
  'sponsorBonus' : IDL.Nat,
  'commissionAmount' : CommissionAmount,
  'productPrice' : IDL.Nat,
});
export const PreWhatsAppContactForm = IDL.Record({
  'customerName' : IDL.Text,
  'productId' : IDL.Nat,
  'customerAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'coordinates' : Coordinates,
});
export const FormSubmissionStatus = IDL.Variant({
  'Error' : IDL.Text,
  'Success' : ContactFormId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'approveMembershipRequest' : IDL.Func([IDL.Nat], [], []),
  'approveWithdrawal' : IDL.Func([WithdrawalId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPurchase' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAchievements' : IDL.Func([MemberId], [IDL.Vec(Achievement)], ['query']),
  'getAllByStatus' : IDL.Func(
      [WithdrawalStatus],
      [IDL.Vec(Withdrawal)],
      ['query'],
    ),
  'getAllContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllMembers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(MemberId, MemberProfile))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getApprovedWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmission' : IDL.Func(
      [ContactFormId],
      [IDL.Opt(ContactFormSubmission)],
      ['query'],
    ),
  'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFamilyTree' : IDL.Func([MemberId], [FamilyTreeNode], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Variant({ 'DownlineCount' : IDL.Null, 'SalesVolume' : IDL.Null })],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getMemberProfile' : IDL.Func([MemberId], [MemberProfile], ['query']),
  'getMemberWithdrawalSummary' : IDL.Func(
      [MemberId],
      [
        IDL.Record({
          'availableBalance' : IDL.Nat,
          'pendingWithdrawals' : IDL.Nat,
          'totalWithdrawn' : IDL.Nat,
          'rejectedWithdrawals' : IDL.Nat,
          'approvedWithdrawals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMemberWithdrawals' : IDL.Func(
      [MemberId],
      [IDL.Vec(Withdrawal)],
      ['query'],
    ),
  'getOwnMemberProfile' : IDL.Func([], [MemberProfile], ['query']),
  'getPendingWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductPrice' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
  'getProfessionalIncentiveScheme' : IDL.Func(
      [],
      [
        IDL.Record({
          'note' : IDL.Text,
          'incentiveComponents' : IDL.Vec(IncentiveComponent),
        }),
      ],
      ['query'],
    ),
  'getPurchase' : IDL.Func([IDL.Nat], [IDL.Opt(Purchase)], ['query']),
  'getSubscriptionVerificationStatus' : IDL.Func(
      [MemberId],
      [IDL.Bool],
      ['query'],
    ),
  'getThemeSettings' : IDL.Func([], [Theme], ['query']),
  'getTransactions' : IDL.Func([MemberId], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberProfile)],
      ['query'],
    ),
  'getWithdrawal' : IDL.Func([WithdrawalId], [IDL.Opt(Withdrawal)], ['query']),
  'hasCompletedSubscription' : IDL.Func([MemberId], [IDL.Bool], ['query']),
  'hasUserPermission' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeDefaultInternetPackages' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'markWithdrawalAsPaid' : IDL.Func([WithdrawalId], [], []),
  'processPurchaseWithCommissions' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'recordAchievement' : IDL.Func([IDL.Text], [], []),
  'recordSales' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'registerMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(MemberId),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'rejectMembershipRequest' : IDL.Func([IDL.Nat], [], []),
  'rejectWithdrawal' : IDL.Func([WithdrawalId], [], []),
  'removeMember' : IDL.Func([MemberId], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat], [WithdrawalId], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Opt(MemberId),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Coordinates, IDL.Nat],
      [ContactFormId],
      [],
    ),
  'submitMembershipRequest' : IDL.Func([MemberProfile], [], []),
  'submitPreWhatsAppContactForm' : IDL.Func(
      [PreWhatsAppContactForm],
      [FormSubmissionStatus],
      [],
    ),
  'updatePurchaseStatus' : IDL.Func([IDL.Nat, PurchaseStatus], [], []),
  'updateSubscriptionVerificationStatus' : IDL.Func([MemberId], [], ['oneway']),
  'validateAdmin' : IDL.Func([], [], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FamilyTreeNode = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const WithdrawalId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberId = IDL.Principal;
  const Time = IDL.Int;
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'memberId' : MemberId,
    'achievedAt' : Time,
    'description' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Withdrawal = IDL.Record({
    'status' : WithdrawalStatus,
    'memberId' : MemberId,
    'requestId' : WithdrawalId,
    'bankAccount' : IDL.Text,
    'amount' : IDL.Nat,
    'requestDate' : Time,
  });
  const ContactFormId = IDL.Nat;
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ContactFormSubmission = IDL.Record({
    'id' : ContactFormId,
    'customerName' : IDL.Text,
    'packagePrice' : IDL.Nat,
    'submittedAt' : Time,
    'submittedBy' : MemberId,
    'productId' : IDL.Nat,
    'customerAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const RegistrationFields = IDL.Record({
    'placeOfBirth' : IDL.Opt(IDL.Text),
    'country' : IDL.Opt(IDL.Text),
    'province' : IDL.Opt(IDL.Text),
    'bankAccount' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Opt(IDL.Text),
    'sameAsKtp' : IDL.Opt(IDL.Bool),
    'city' : IDL.Opt(IDL.Text),
    'completeAddress' : IDL.Opt(IDL.Text),
    'sponsorId' : IDL.Opt(MemberId),
    'fullName' : IDL.Opt(IDL.Text),
    'sealed' : IDL.Bool,
    'whatsappNumber' : IDL.Opt(IDL.Text),
    'subscriptionsVerified' : IDL.Bool,
    'nikKtp' : IDL.Opt(IDL.Text),
    'domicileAddress' : IDL.Opt(IDL.Text),
  });
  const ProfileCompletionStatus = IDL.Variant({
    'incomplete' : IDL.Null,
    'complete' : IDL.Null,
  });
  const BasicProfile = IDL.Record({
    'contact' : IDL.Text,
    'joinDate' : Time,
    'name' : IDL.Text,
  });
  const MemberProfile = IDL.Record({
    'profileCompletionTimestamp' : IDL.Opt(Time),
    'registrationFields' : RegistrationFields,
    'profileCompletionStatus' : ProfileCompletionStatus,
    'basic' : BasicProfile,
    'profileRole' : UserRole,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'explanation' : IDL.Text,
    'description' : IDL.Text,
    'commissionRate' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const PurchaseStatus = IDL.Variant({
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Purchase = IDL.Record({
    'id' : IDL.Nat,
    'status' : PurchaseStatus,
    'contact' : IDL.Text,
    'purchaseDate' : Time,
    'productId' : IDL.Nat,
    'address' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  FamilyTreeNode.fill(
    IDL.Record({
      'memberId' : MemberId,
      'registrationFields' : RegistrationFields,
      'children' : IDL.Vec(FamilyTreeNode),
      'basic' : BasicProfile,
    })
  );
  const IncentiveComponent = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const Theme = IDL.Record({
    'backgroundColor' : IDL.Text,
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const Level = IDL.Nat;
  const CommissionAmount = IDL.Nat;
  const Transaction = IDL.Record({
    'memberId' : MemberId,
    'date' : Time,
    'level' : Level,
    'sponsorBonus' : IDL.Nat,
    'commissionAmount' : CommissionAmount,
    'productPrice' : IDL.Nat,
  });
  const PreWhatsAppContactForm = IDL.Record({
    'customerName' : IDL.Text,
    'productId' : IDL.Nat,
    'customerAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const FormSubmissionStatus = IDL.Variant({
    'Error' : IDL.Text,
    'Success' : ContactFormId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'approveMembershipRequest' : IDL.Func([IDL.Nat], [], []),
    'approveWithdrawal' : IDL.Func([WithdrawalId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPurchase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'getAchievements' : IDL.Func([MemberId], [IDL.Vec(Achievement)], ['query']),
    'getAllByStatus' : IDL.Func(
        [WithdrawalStatus],
        [IDL.Vec(Withdrawal)],
        ['query'],
      ),
    'getAllContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllMembers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(MemberId, MemberProfile))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getApprovedWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmission' : IDL.Func(
        [ContactFormId],
        [IDL.Opt(ContactFormSubmission)],
        ['query'],
      ),
    'getCurrentUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFamilyTree' : IDL.Func([MemberId], [FamilyTreeNode], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Variant({ 'DownlineCount' : IDL.Null, 'SalesVolume' : IDL.Null })],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getMemberProfile' : IDL.Func([MemberId], [MemberProfile], ['query']),
    'getMemberWithdrawalSummary' : IDL.Func(
        [MemberId],
        [
          IDL.Record({
            'availableBalance' : IDL.Nat,
            'pendingWithdrawals' : IDL.Nat,
            'totalWithdrawn' : IDL.Nat,
            'rejectedWithdrawals' : IDL.Nat,
            'approvedWithdrawals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMemberWithdrawals' : IDL.Func(
        [MemberId],
        [IDL.Vec(Withdrawal)],
        ['query'],
      ),
    'getOwnMemberProfile' : IDL.Func([], [MemberProfile], ['query']),
    'getPendingWithdrawals' : IDL.Func([], [IDL.Vec(Withdrawal)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductPrice' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Nat)], ['query']),
    'getProfessionalIncentiveScheme' : IDL.Func(
        [],
        [
          IDL.Record({
            'note' : IDL.Text,
            'incentiveComponents' : IDL.Vec(IncentiveComponent),
          }),
        ],
        ['query'],
      ),
    'getPurchase' : IDL.Func([IDL.Nat], [IDL.Opt(Purchase)], ['query']),
    'getSubscriptionVerificationStatus' : IDL.Func(
        [MemberId],
        [IDL.Bool],
        ['query'],
      ),
    'getThemeSettings' : IDL.Func([], [Theme], ['query']),
    'getTransactions' : IDL.Func([MemberId], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberProfile)],
        ['query'],
      ),
    'getWithdrawal' : IDL.Func(
        [WithdrawalId],
        [IDL.Opt(Withdrawal)],
        ['query'],
      ),
    'hasCompletedSubscription' : IDL.Func([MemberId], [IDL.Bool], ['query']),
    'hasUserPermission' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeDefaultInternetPackages' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'markWithdrawalAsPaid' : IDL.Func([WithdrawalId], [], []),
    'processPurchaseWithCommissions' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'recordAchievement' : IDL.Func([IDL.Text], [], []),
    'recordSales' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'registerMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(MemberId),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'rejectMembershipRequest' : IDL.Func([IDL.Nat], [], []),
    'rejectWithdrawal' : IDL.Func([WithdrawalId], [], []),
    'removeMember' : IDL.Func([MemberId], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat], [WithdrawalId], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Opt(MemberId),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Coordinates, IDL.Nat],
        [ContactFormId],
        [],
      ),
    'submitMembershipRequest' : IDL.Func([MemberProfile], [], []),
    'submitPreWhatsAppContactForm' : IDL.Func(
        [PreWhatsAppContactForm],
        [FormSubmissionStatus],
        [],
      ),
    'updatePurchaseStatus' : IDL.Func([IDL.Nat, PurchaseStatus], [], []),
    'updateSubscriptionVerificationStatus' : IDL.Func(
        [MemberId],
        [],
        ['oneway'],
      ),
    'validateAdmin' : IDL.Func([], [], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };