/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'memberId' : MemberId,
  'achievedAt' : Time,
  'description' : string,
}
export interface BasicProfile {
  'contact' : string,
  'joinDate' : Time,
  'name' : string,
}
export type CommissionAmount = bigint;
export type ContactFormId = bigint;
export interface ContactFormSubmission {
  'id' : ContactFormId,
  'customerName' : string,
  'packagePrice' : bigint,
  'submittedAt' : Time,
  'submittedBy' : MemberId,
  'productId' : bigint,
  'customerAddress' : string,
  'phoneNumber' : string,
  'coordinates' : Coordinates,
}
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface FamilyTreeNode {
  'memberId' : MemberId,
  'registrationFields' : RegistrationFields,
  'children' : Array<FamilyTreeNode>,
  'basic' : BasicProfile,
}
export type FormSubmissionStatus = { 'Error' : string } |
  { 'Success' : ContactFormId };
export interface IncentiveComponent {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'percentage' : number,
}
export type Level = bigint;
export type MemberId = Principal;
export interface MemberProfile {
  'profileCompletionTimestamp' : [] | [Time],
  'registrationFields' : RegistrationFields,
  'profileCompletionStatus' : ProfileCompletionStatus,
  'basic' : BasicProfile,
  'profileRole' : UserRole,
}
export interface PreWhatsAppContactForm {
  'customerName' : string,
  'productId' : bigint,
  'customerAddress' : string,
  'phoneNumber' : string,
  'coordinates' : Coordinates,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'explanation' : string,
  'description' : string,
  'commissionRate' : bigint,
  'price' : bigint,
}
export type ProfileCompletionStatus = { 'incomplete' : null } |
  { 'complete' : null };
export interface Purchase {
  'id' : bigint,
  'status' : PurchaseStatus,
  'contact' : string,
  'purchaseDate' : Time,
  'productId' : bigint,
  'address' : string,
  'buyerName' : string,
}
export type PurchaseStatus = { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface RegistrationFields {
  'placeOfBirth' : [] | [string],
  'country' : [] | [string],
  'province' : [] | [string],
  'bankAccount' : [] | [string],
  'dateOfBirth' : [] | [string],
  'sameAsKtp' : [] | [boolean],
  'city' : [] | [string],
  'completeAddress' : [] | [string],
  'sponsorId' : [] | [MemberId],
  'fullName' : [] | [string],
  'sealed' : boolean,
  'whatsappNumber' : [] | [string],
  'subscriptionsVerified' : boolean,
  'nikKtp' : [] | [string],
  'domicileAddress' : [] | [string],
}
export interface Theme {
  'backgroundColor' : string,
  'primaryColor' : string,
  'accentColor' : string,
  'secondaryColor' : string,
}
export type Time = bigint;
export interface Transaction {
  'memberId' : MemberId,
  'date' : Time,
  'level' : Level,
  'sponsorBonus' : bigint,
  'commissionAmount' : CommissionAmount,
  'productPrice' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Withdrawal {
  'status' : WithdrawalStatus,
  'memberId' : MemberId,
  'requestId' : WithdrawalId,
  'bankAccount' : string,
  'amount' : bigint,
  'requestDate' : Time,
}
export type WithdrawalId = bigint;
export type WithdrawalStatus = { 'Paid' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, bigint, string],
    undefined
  >,
  'approveMembershipRequest' : ActorMethod<[bigint], undefined>,
  'approveWithdrawal' : ActorMethod<[WithdrawalId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPurchase' : ActorMethod<[string, string, string, bigint], undefined>,
  'getAchievements' : ActorMethod<[MemberId], Array<Achievement>>,
  'getAllByStatus' : ActorMethod<[WithdrawalStatus], Array<Withdrawal>>,
  'getAllContactFormSubmissions' : ActorMethod<
    [],
    Array<ContactFormSubmission>
  >,
  'getAllMembers' : ActorMethod<[], Array<[MemberId, MemberProfile]>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'getAllWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getApprovedWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [MemberProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormSubmission' : ActorMethod<
    [ContactFormId],
    [] | [ContactFormSubmission]
  >,
  'getCurrentUserRole' : ActorMethod<[], UserRole>,
  'getFamilyTree' : ActorMethod<[MemberId], FamilyTreeNode>,
  'getLeaderboard' : ActorMethod<
    [{ 'DownlineCount' : null } | { 'SalesVolume' : null }],
    Array<[Principal, bigint]>
  >,
  'getMemberProfile' : ActorMethod<[MemberId], MemberProfile>,
  'getMemberWithdrawalSummary' : ActorMethod<
    [MemberId],
    {
      'availableBalance' : bigint,
      'pendingWithdrawals' : bigint,
      'totalWithdrawn' : bigint,
      'rejectedWithdrawals' : bigint,
      'approvedWithdrawals' : bigint,
    }
  >,
  'getMemberWithdrawals' : ActorMethod<[MemberId], Array<Withdrawal>>,
  'getOwnMemberProfile' : ActorMethod<[], MemberProfile>,
  'getPendingWithdrawals' : ActorMethod<[], Array<Withdrawal>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductPrice' : ActorMethod<[bigint], [] | [bigint]>,
  'getProfessionalIncentiveScheme' : ActorMethod<
    [],
    { 'note' : string, 'incentiveComponents' : Array<IncentiveComponent> }
  >,
  'getPurchase' : ActorMethod<[bigint], [] | [Purchase]>,
  'getSubscriptionVerificationStatus' : ActorMethod<[MemberId], boolean>,
  'getThemeSettings' : ActorMethod<[], Theme>,
  'getTransactions' : ActorMethod<[MemberId], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [MemberProfile]>,
  'getWithdrawal' : ActorMethod<[WithdrawalId], [] | [Withdrawal]>,
  'hasCompletedSubscription' : ActorMethod<[MemberId], boolean>,
  'hasUserPermission' : ActorMethod<[], boolean>,
  'initializeDefaultInternetPackages' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProfileComplete' : ActorMethod<[], boolean>,
  'markWithdrawalAsPaid' : ActorMethod<[WithdrawalId], undefined>,
  'processPurchaseWithCommissions' : ActorMethod<
    [string, string, string, bigint],
    undefined
  >,
  'recordAchievement' : ActorMethod<[string], undefined>,
  'recordSales' : ActorMethod<[bigint, bigint], undefined>,
  'registerMember' : ActorMethod<
    [
      string,
      string,
      [] | [MemberId],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [string],
    ],
    undefined
  >,
  'rejectMembershipRequest' : ActorMethod<[bigint], undefined>,
  'rejectWithdrawal' : ActorMethod<[WithdrawalId], undefined>,
  'removeMember' : ActorMethod<[MemberId], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint], WithdrawalId>,
  'saveCallerUserProfile' : ActorMethod<
    [
      [] | [MemberId],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [boolean],
      [] | [string],
    ],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, Coordinates, bigint],
    ContactFormId
  >,
  'submitMembershipRequest' : ActorMethod<[MemberProfile], undefined>,
  'submitPreWhatsAppContactForm' : ActorMethod<
    [PreWhatsAppContactForm],
    FormSubmissionStatus
  >,
  'updatePurchaseStatus' : ActorMethod<[bigint, PurchaseStatus], undefined>,
  'updateSubscriptionVerificationStatus' : ActorMethod<[MemberId], undefined>,
  'validateAdmin' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];