/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Product {
    id: bigint;
    name: string;
    explanation: string;
    description: string;
    commissionRate: bigint;
    price: bigint;
}
export type Time = bigint;
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ContactFormId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BasicProfile {
    contact: string;
    joinDate: Time;
    name: string;
}
export interface MemberProfile {
    profileCompletionTimestamp?: Time;
    registrationFields: RegistrationFields;
    profileCompletionStatus: ProfileCompletionStatus;
    basic: BasicProfile;
    profileRole: UserRole;
}
export interface Transaction {
    memberId: MemberId;
    date: Time;
    level: Level;
    sponsorBonus: bigint;
    commissionAmount: CommissionAmount;
    productPrice: bigint;
}
export interface ContactFormSubmission {
    id: ContactFormId;
    customerName: string;
    packagePrice: bigint;
    submittedAt: Time;
    submittedBy: MemberId;
    productId: bigint;
    customerAddress: string;
    phoneNumber: string;
    coordinates: Coordinates;
}
export interface Achievement {
    id: bigint;
    memberId: MemberId;
    achievedAt: Time;
    description: string;
}
export interface IncentiveComponent {
    id: bigint;
    name: string;
    description: string;
    percentage: number;
}
export interface Withdrawal {
    status: WithdrawalStatus;
    memberId: MemberId;
    requestId: WithdrawalId;
    bankAccount: string;
    amount: bigint;
    requestDate: Time;
}
export interface RegistrationFields {
    placeOfBirth?: string;
    country?: string;
    province?: string;
    bankAccount?: string;
    dateOfBirth?: string;
    sameAsKtp?: boolean;
    city?: string;
    completeAddress?: string;
    sponsorId?: MemberId;
    fullName?: string;
    sealed: boolean;
    whatsappNumber?: string;
    subscriptionsVerified: boolean;
    nikKtp?: string;
    domicileAddress?: string;
}
export interface Purchase {
    id: bigint;
    status: PurchaseStatus;
    contact: string;
    purchaseDate: Time;
    productId: bigint;
    address: string;
    buyerName: string;
}
export interface Theme {
    backgroundColor: string;
    primaryColor: string;
    accentColor: string;
    secondaryColor: string;
}
export interface FamilyTreeNode {
    memberId: MemberId;
    registrationFields: RegistrationFields;
    children: Array<FamilyTreeNode>;
    basic: BasicProfile;
}
export type MemberId = Principal;
export type CommissionAmount = bigint;
export type WithdrawalId = bigint;
export type FormSubmissionStatus = {
    __kind__: "Error";
    Error: string;
} | {
    __kind__: "Success";
    Success: ContactFormId;
};
export interface PreWhatsAppContactForm {
    customerName: string;
    productId: bigint;
    customerAddress: string;
    phoneNumber: string;
    coordinates: Coordinates;
}
export type Level = bigint;
export enum ProfileCompletionStatus {
    incomplete = "incomplete",
    complete = "complete"
}
export enum PurchaseStatus {
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_DownlineCount_SalesVolume {
    DownlineCount = "DownlineCount",
    SalesVolume = "SalesVolume"
}
export enum WithdrawalStatus {
    Paid = "Paid",
    Approved = "Approved",
    Rejected = "Rejected",
    Pending = "Pending"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(name: string, description: string, price: bigint, commissionRate: bigint, explanation: string): Promise<void>;
    approveMembershipRequest(requestId: bigint): Promise<void>;
    approveWithdrawal(withdrawalId: WithdrawalId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bootstrapDefaultInternetPackagesIfEmpty(): Promise<bigint>;
    createPurchase(buyerName: string, contact: string, address: string, productId: bigint): Promise<void>;
    getAchievements(memberId: MemberId): Promise<Array<Achievement>>;
    getAllByStatus(status: WithdrawalStatus): Promise<Array<Withdrawal>>;
    getAllContactFormSubmissions(): Promise<Array<ContactFormSubmission>>;
    getAllMembers(): Promise<Array<[MemberId, MemberProfile]>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllPurchases(): Promise<Array<Purchase>>;
    getAllWithdrawals(): Promise<Array<Withdrawal>>;
    getApprovedWithdrawals(): Promise<Array<Withdrawal>>;
    getCallerUserProfile(): Promise<MemberProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactFormSubmission(submissionId: ContactFormId): Promise<ContactFormSubmission | null>;
    getCurrentUserRole(): Promise<UserRole>;
    getFamilyTree(memberId: MemberId): Promise<FamilyTreeNode>;
    getLeaderboard(leaderboardType: Variant_DownlineCount_SalesVolume): Promise<Array<[Principal, bigint]>>;
    getMemberProfile(memberId: MemberId): Promise<MemberProfile>;
    getMemberWithdrawalSummary(memberId: MemberId): Promise<{
        availableBalance: bigint;
        pendingWithdrawals: bigint;
        totalWithdrawn: bigint;
        rejectedWithdrawals: bigint;
        approvedWithdrawals: bigint;
    }>;
    getMemberWithdrawals(memberId: MemberId): Promise<Array<Withdrawal>>;
    getOwnMemberProfile(): Promise<MemberProfile>;
    getPendingWithdrawals(): Promise<Array<Withdrawal>>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductPrice(productId: bigint): Promise<bigint | null>;
    getProfessionalIncentiveScheme(): Promise<{
        note: string;
        incentiveComponents: Array<IncentiveComponent>;
    }>;
    getPurchase(purchaseId: bigint): Promise<Purchase | null>;
    getSubscriptionVerificationStatus(memberId: MemberId): Promise<boolean>;
    getThemeSettings(): Promise<Theme>;
    getTransactions(memberId: MemberId): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<MemberProfile | null>;
    getWithdrawal(withdrawalId: WithdrawalId): Promise<Withdrawal | null>;
    hasCompletedSubscription(memberId: MemberId): Promise<boolean>;
    hasUserPermission(): Promise<boolean>;
    initializeDefaultInternetPackages(): Promise<void>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isProfileComplete(): Promise<boolean>;
    markWithdrawalAsPaid(withdrawalId: WithdrawalId): Promise<void>;
    processPurchaseWithCommissions(buyerName: string, contact: string, address: string, productId: bigint): Promise<void>;
    recordAchievement(description: string): Promise<void>;
    recordSales(productId: bigint, quantity: bigint): Promise<void>;
    registerMember(name: string, contact: string, sponsorId: MemberId | null, nikKtp: string | null, fullName: string | null, placeOfBirth: string | null, dateOfBirth: string | null, completeAddress: string | null, province: string | null, city: string | null, country: string | null, whatsappNumber: string | null, domicileAddress: string | null, sameAsKtp: boolean | null, bankAccount: string | null): Promise<void>;
    rejectMembershipRequest(requestId: bigint): Promise<void>;
    rejectWithdrawal(withdrawalId: WithdrawalId): Promise<void>;
    removeMember(memberId: MemberId): Promise<void>;
    requestWithdrawal(amount: bigint): Promise<WithdrawalId>;
    saveCallerUserProfile(sponsorId: MemberId | null, nikKtp: string | null, fullName: string | null, placeOfBirth: string | null, dateOfBirth: string | null, completeAddress: string | null, province: string | null, city: string | null, country: string | null, whatsappNumber: string | null, domicileAddress: string | null, sameAsKtp: boolean | null, bankAccount: string | null): Promise<void>;
    submitContactForm(customerName: string, phoneNumber: string, customerAddress: string, coordinates: Coordinates, productId: bigint): Promise<ContactFormId>;
    submitMembershipRequest(profile: MemberProfile): Promise<void>;
    submitPreWhatsAppContactForm(form: PreWhatsAppContactForm): Promise<FormSubmissionStatus>;
    updatePurchaseStatus(purchaseId: bigint, status: PurchaseStatus): Promise<void>;
    updateSubscriptionVerificationStatus(memberId: MemberId): Promise<void>;
    validateAdmin(): Promise<void>;
}
import type { BasicProfile as _BasicProfile, ContactFormId as _ContactFormId, ContactFormSubmission as _ContactFormSubmission, FamilyTreeNode as _FamilyTreeNode, FormSubmissionStatus as _FormSubmissionStatus, MemberId as _MemberId, MemberProfile as _MemberProfile, Product as _Product, ProfileCompletionStatus as _ProfileCompletionStatus, Purchase as _Purchase, PurchaseStatus as _PurchaseStatus, RegistrationFields as _RegistrationFields, Time as _Time, UserRole as _UserRole, Withdrawal as _Withdrawal, WithdrawalId as _WithdrawalId, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async approveMembershipRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMembershipRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMembershipRequest(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: WithdrawalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bootstrapDefaultInternetPackagesIfEmpty(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bootstrapDefaultInternetPackagesIfEmpty();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bootstrapDefaultInternetPackagesIfEmpty();
            return result;
        }
    }
    async createPurchase(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchase(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchase(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAchievements(arg0: MemberId): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements(arg0);
            return result;
        }
    }
    async getAllByStatus(arg0: WithdrawalStatus): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllByStatus(to_candid_WithdrawalStatus_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllByStatus(to_candid_WithdrawalStatus_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContactFormSubmissions(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactFormSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactFormSubmissions();
            return result;
        }
    }
    async getAllMembers(): Promise<Array<[MemberId, MemberProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllPurchases(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchases();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchases();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<MemberProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactFormSubmission(arg0: ContactFormId): Promise<ContactFormSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactFormSubmission(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactFormSubmission(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyTree(arg0: MemberId): Promise<FamilyTreeNode> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyTree(arg0);
                return from_candid_FamilyTreeNode_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyTree(arg0);
            return from_candid_FamilyTreeNode_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: Variant_DownlineCount_SalesVolume): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_variant_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_variant_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getMemberProfile(arg0: MemberId): Promise<MemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberProfile(arg0);
                return from_candid_MemberProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberProfile(arg0);
            return from_candid_MemberProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemberWithdrawalSummary(arg0: MemberId): Promise<{
        availableBalance: bigint;
        pendingWithdrawals: bigint;
        totalWithdrawn: bigint;
        rejectedWithdrawals: bigint;
        approvedWithdrawals: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberWithdrawalSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberWithdrawalSummary(arg0);
            return result;
        }
    }
    async getMemberWithdrawals(arg0: MemberId): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemberWithdrawals(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemberWithdrawals(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnMemberProfile(): Promise<MemberProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnMemberProfile();
                return from_candid_MemberProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnMemberProfile();
            return from_candid_MemberProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingWithdrawals(): Promise<Array<Withdrawal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingWithdrawals();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingWithdrawals();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductPrice(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductPrice(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductPrice(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfessionalIncentiveScheme(): Promise<{
        note: string;
        incentiveComponents: Array<IncentiveComponent>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfessionalIncentiveScheme();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfessionalIncentiveScheme();
            return result;
        }
    }
    async getPurchase(arg0: bigint): Promise<Purchase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchase(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchase(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionVerificationStatus(arg0: MemberId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionVerificationStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionVerificationStatus(arg0);
            return result;
        }
    }
    async getThemeSettings(): Promise<Theme> {
        if (this.processError) {
            try {
                const result = await this.actor.getThemeSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThemeSettings();
            return result;
        }
    }
    async getTransactions(arg0: MemberId): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<MemberProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawal(arg0: WithdrawalId): Promise<Withdrawal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawal(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawal(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasCompletedSubscription(arg0: MemberId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasCompletedSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasCompletedSubscription(arg0);
            return result;
        }
    }
    async hasUserPermission(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserPermission();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserPermission();
            return result;
        }
    }
    async initializeDefaultInternetPackages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultInternetPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultInternetPackages();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isProfileComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProfileComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProfileComplete();
            return result;
        }
    }
    async markWithdrawalAsPaid(arg0: WithdrawalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWithdrawalAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWithdrawalAsPaid(arg0);
            return result;
        }
    }
    async processPurchaseWithCommissions(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processPurchaseWithCommissions(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processPurchaseWithCommissions(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async recordAchievement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAchievement(arg0);
            return result;
        }
    }
    async recordSales(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSales(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSales(arg0, arg1);
            return result;
        }
    }
    async registerMember(arg0: string, arg1: string, arg2: MemberId | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string | null, arg9: string | null, arg10: string | null, arg11: string | null, arg12: string | null, arg13: boolean | null, arg14: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMember(arg0, arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg14));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMember(arg0, arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg13), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg14));
            return result;
        }
    }
    async rejectMembershipRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectMembershipRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectMembershipRequest(arg0);
            return result;
        }
    }
    async rejectWithdrawal(arg0: WithdrawalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async removeMember(arg0: MemberId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint): Promise<WithdrawalId> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: MemberId | null, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string | null, arg9: string | null, arg10: string | null, arg11: boolean | null, arg12: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg12));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n46(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n45(this._uploadFile, this._downloadFile, arg12));
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: Coordinates, arg4: bigint): Promise<ContactFormId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async submitMembershipRequest(arg0: MemberProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMembershipRequest(to_candid_MemberProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMembershipRequest(to_candid_MemberProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitPreWhatsAppContactForm(arg0: PreWhatsAppContactForm): Promise<FormSubmissionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPreWhatsAppContactForm(arg0);
                return from_candid_FormSubmissionStatus_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPreWhatsAppContactForm(arg0);
            return from_candid_FormSubmissionStatus_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePurchaseStatus(arg0: bigint, arg1: PurchaseStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseStatus(arg0, to_candid_PurchaseStatus_n55(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseStatus(arg0, to_candid_PurchaseStatus_n55(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubscriptionVerificationStatus(arg0: MemberId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionVerificationStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionVerificationStatus(arg0);
            return result;
        }
    }
    async validateAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdmin();
            return result;
        }
    }
}
function from_candid_FamilyTreeNode_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FamilyTreeNode): FamilyTreeNode {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_FormSubmissionStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormSubmissionStatus): FormSubmissionStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_MemberProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MemberProfile): MemberProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileCompletionStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileCompletionStatus): ProfileCompletionStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseStatus): PurchaseStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Purchase_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Purchase): Purchase {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_RegistrationFields_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegistrationFields): RegistrationFields {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Withdrawal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Withdrawal): Withdrawal {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberId]): MemberId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MemberProfile]): MemberProfile | null {
    return value.length === 0 ? null : from_candid_MemberProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactFormSubmission]): ContactFormSubmission | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Purchase]): Purchase | null {
    return value.length === 0 ? null : from_candid_Purchase_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Withdrawal]): Withdrawal | null {
    return value.length === 0 ? null : from_candid_Withdrawal_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _WithdrawalStatus;
    memberId: _MemberId;
    requestId: _WithdrawalId;
    bankAccount: string;
    amount: bigint;
    requestDate: _Time;
}): {
    status: WithdrawalStatus;
    memberId: MemberId;
    requestId: WithdrawalId;
    bankAccount: string;
    amount: bigint;
    requestDate: Time;
} {
    return {
        status: from_candid_WithdrawalStatus_n15(_uploadFile, _downloadFile, value.status),
        memberId: value.memberId,
        requestId: value.requestId,
        bankAccount: value.bankAccount,
        amount: value.amount,
        requestDate: value.requestDate
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileCompletionTimestamp: [] | [_Time];
    registrationFields: _RegistrationFields;
    profileCompletionStatus: _ProfileCompletionStatus;
    basic: _BasicProfile;
    profileRole: _UserRole;
}): {
    profileCompletionTimestamp?: Time;
    registrationFields: RegistrationFields;
    profileCompletionStatus: ProfileCompletionStatus;
    basic: BasicProfile;
    profileRole: UserRole;
} {
    return {
        profileCompletionTimestamp: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.profileCompletionTimestamp)),
        registrationFields: from_candid_RegistrationFields_n22(_uploadFile, _downloadFile, value.registrationFields),
        profileCompletionStatus: from_candid_ProfileCompletionStatus_n26(_uploadFile, _downloadFile, value.profileCompletionStatus),
        basic: value.basic,
        profileRole: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.profileRole)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfBirth: [] | [string];
    country: [] | [string];
    province: [] | [string];
    bankAccount: [] | [string];
    dateOfBirth: [] | [string];
    sameAsKtp: [] | [boolean];
    city: [] | [string];
    completeAddress: [] | [string];
    sponsorId: [] | [_MemberId];
    fullName: [] | [string];
    sealed: boolean;
    whatsappNumber: [] | [string];
    subscriptionsVerified: boolean;
    nikKtp: [] | [string];
    domicileAddress: [] | [string];
}): {
    placeOfBirth?: string;
    country?: string;
    province?: string;
    bankAccount?: string;
    dateOfBirth?: string;
    sameAsKtp?: boolean;
    city?: string;
    completeAddress?: string;
    sponsorId?: MemberId;
    fullName?: string;
    sealed: boolean;
    whatsappNumber?: string;
    subscriptionsVerified: boolean;
    nikKtp?: string;
    domicileAddress?: string;
} {
    return {
        placeOfBirth: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.placeOfBirth)),
        country: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.country)),
        province: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.province)),
        bankAccount: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.bankAccount)),
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.dateOfBirth)),
        sameAsKtp: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.sameAsKtp)),
        city: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.city)),
        completeAddress: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.completeAddress)),
        sponsorId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.sponsorId)),
        fullName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.fullName)),
        sealed: value.sealed,
        whatsappNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.whatsappNumber)),
        subscriptionsVerified: value.subscriptionsVerified,
        nikKtp: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.nikKtp)),
        domicileAddress: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.domicileAddress))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PurchaseStatus;
    contact: string;
    purchaseDate: _Time;
    productId: bigint;
    address: string;
    buyerName: string;
}): {
    id: bigint;
    status: PurchaseStatus;
    contact: string;
    purchaseDate: Time;
    productId: bigint;
    address: string;
    buyerName: string;
} {
    return {
        id: value.id,
        status: from_candid_PurchaseStatus_n33(_uploadFile, _downloadFile, value.status),
        contact: value.contact,
        purchaseDate: value.purchaseDate,
        productId: value.productId,
        address: value.address,
        buyerName: value.buyerName
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    memberId: _MemberId;
    registrationFields: _RegistrationFields;
    children: Array<_FamilyTreeNode>;
    basic: _BasicProfile;
}): {
    memberId: MemberId;
    registrationFields: RegistrationFields;
    children: Array<FamilyTreeNode>;
    basic: BasicProfile;
} {
    return {
        memberId: value.memberId,
        registrationFields: from_candid_RegistrationFields_n22(_uploadFile, _downloadFile, value.registrationFields),
        children: from_candid_vec_n39(_uploadFile, _downloadFile, value.children),
        basic: value.basic
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_MemberId, _MemberProfile]): [MemberId, MemberProfile] {
    return [
        value[0],
        from_candid_MemberProfile_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
}): WithdrawalStatus {
    return "Paid" in value ? WithdrawalStatus.Paid : "Approved" in value ? WithdrawalStatus.Approved : "Rejected" in value ? WithdrawalStatus.Rejected : "Pending" in value ? WithdrawalStatus.Pending : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    incomplete: null;
} | {
    complete: null;
}): ProfileCompletionStatus {
    return "incomplete" in value ? ProfileCompletionStatus.incomplete : "complete" in value ? ProfileCompletionStatus.complete : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): PurchaseStatus {
    return "Cancelled" in value ? PurchaseStatus.Cancelled : "Completed" in value ? PurchaseStatus.Completed : "Pending" in value ? PurchaseStatus.Pending : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Error: string;
} | {
    Success: _ContactFormId;
}): {
    __kind__: "Error";
    Error: string;
} | {
    __kind__: "Success";
    Success: ContactFormId;
} {
    return "Error" in value ? {
        __kind__: "Error",
        Error: value.Error
    } : "Success" in value ? {
        __kind__: "Success",
        Success: value.Success
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Withdrawal>): Array<Withdrawal> {
    return value.map((x)=>from_candid_Withdrawal_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_MemberId, _MemberProfile]>): Array<[MemberId, MemberProfile]> {
    return value.map((x)=>from_candid_tuple_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Purchase>): Array<Purchase> {
    return value.map((x)=>from_candid_Purchase_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FamilyTreeNode>): Array<FamilyTreeNode> {
    return value.map((x)=>from_candid_FamilyTreeNode_n37(_uploadFile, _downloadFile, x));
}
function to_candid_MemberProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberProfile): _MemberProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileCompletionStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileCompletionStatus): _ProfileCompletionStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_PurchaseStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseStatus): _PurchaseStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_RegistrationFields_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegistrationFields): _RegistrationFields {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): _WithdrawalStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MemberId | null): [] | [_MemberId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileCompletionTimestamp?: Time;
    registrationFields: RegistrationFields;
    profileCompletionStatus: ProfileCompletionStatus;
    basic: BasicProfile;
    profileRole: UserRole;
}): {
    profileCompletionTimestamp: [] | [_Time];
    registrationFields: _RegistrationFields;
    profileCompletionStatus: _ProfileCompletionStatus;
    basic: _BasicProfile;
    profileRole: _UserRole;
} {
    return {
        profileCompletionTimestamp: value.profileCompletionTimestamp ? candid_some(value.profileCompletionTimestamp) : candid_none(),
        registrationFields: to_candid_RegistrationFields_n49(_uploadFile, _downloadFile, value.registrationFields),
        profileCompletionStatus: to_candid_ProfileCompletionStatus_n51(_uploadFile, _downloadFile, value.profileCompletionStatus),
        basic: value.basic,
        profileRole: to_candid_UserRole_n8(_uploadFile, _downloadFile, value.profileRole)
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfBirth?: string;
    country?: string;
    province?: string;
    bankAccount?: string;
    dateOfBirth?: string;
    sameAsKtp?: boolean;
    city?: string;
    completeAddress?: string;
    sponsorId?: MemberId;
    fullName?: string;
    sealed: boolean;
    whatsappNumber?: string;
    subscriptionsVerified: boolean;
    nikKtp?: string;
    domicileAddress?: string;
}): {
    placeOfBirth: [] | [string];
    country: [] | [string];
    province: [] | [string];
    bankAccount: [] | [string];
    dateOfBirth: [] | [string];
    sameAsKtp: [] | [boolean];
    city: [] | [string];
    completeAddress: [] | [string];
    sponsorId: [] | [_MemberId];
    fullName: [] | [string];
    sealed: boolean;
    whatsappNumber: [] | [string];
    subscriptionsVerified: boolean;
    nikKtp: [] | [string];
    domicileAddress: [] | [string];
} {
    return {
        placeOfBirth: value.placeOfBirth ? candid_some(value.placeOfBirth) : candid_none(),
        country: value.country ? candid_some(value.country) : candid_none(),
        province: value.province ? candid_some(value.province) : candid_none(),
        bankAccount: value.bankAccount ? candid_some(value.bankAccount) : candid_none(),
        dateOfBirth: value.dateOfBirth ? candid_some(value.dateOfBirth) : candid_none(),
        sameAsKtp: value.sameAsKtp ? candid_some(value.sameAsKtp) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        completeAddress: value.completeAddress ? candid_some(value.completeAddress) : candid_none(),
        sponsorId: value.sponsorId ? candid_some(value.sponsorId) : candid_none(),
        fullName: value.fullName ? candid_some(value.fullName) : candid_none(),
        sealed: value.sealed,
        whatsappNumber: value.whatsappNumber ? candid_some(value.whatsappNumber) : candid_none(),
        subscriptionsVerified: value.subscriptionsVerified,
        nikKtp: value.nikKtp ? candid_some(value.nikKtp) : candid_none(),
        domicileAddress: value.domicileAddress ? candid_some(value.domicileAddress) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): {
    Paid: null;
} | {
    Approved: null;
} | {
    Rejected: null;
} | {
    Pending: null;
} {
    return value == WithdrawalStatus.Paid ? {
        Paid: null
    } : value == WithdrawalStatus.Approved ? {
        Approved: null
    } : value == WithdrawalStatus.Rejected ? {
        Rejected: null
    } : value == WithdrawalStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_DownlineCount_SalesVolume): {
    DownlineCount: null;
} | {
    SalesVolume: null;
} {
    return value == Variant_DownlineCount_SalesVolume.DownlineCount ? {
        DownlineCount: null
    } : value == Variant_DownlineCount_SalesVolume.SalesVolume ? {
        SalesVolume: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileCompletionStatus): {
    incomplete: null;
} | {
    complete: null;
} {
    return value == ProfileCompletionStatus.incomplete ? {
        incomplete: null
    } : value == ProfileCompletionStatus.complete ? {
        complete: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PurchaseStatus): {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == PurchaseStatus.Cancelled ? {
        Cancelled: null
    } : value == PurchaseStatus.Completed ? {
        Completed: null
    } : value == PurchaseStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
